spring:
  cloud:
    discovery:
      enabled: false
  application:
    name: ChatService
  profiles:
    active: docker

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

redis:
  host: ${REDIS_HOST}

userservice:
  baseUrl: http://userservice:8080


