spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eurekaserver
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

server:
  port: 8761
  address: 0.0.0.0
