server:
  port: 8761
  address: 0.0.0.0

eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
