spring:
  cloud:
    discovery:
      enabled: false
  application:
    name: userservices
  profiles:
    active: docker

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}




